### ISSUE TITLE
[Insight] Text files should end with a newline character - in phpspec.yml, line 20

### ISSUE THREAD

**Issue by m3gg3r** [solutionDrive/HipchatAPIv2Client#10]
**[in phpspec.yml, line 20](https://github.com/solutionDrive/HipchatAPIv2Client/blob/513d47e43a2dd8f10e824169a333735513c536d7/phpspec.yml#L20)**

> This file ends with no newline character. It won't render properly on a terminal, and it's considered a bad practice. Add a simple line feed as the last character to fix it.

```
      - clover
    output:
      html: coverage
      clover: coverage.clover
    lower_upper_bound: 50
    high_lower_bound: 90
```

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/fe1dde4f-3158-45db-8f9a-315f97f2cd54/analyses/19)_
